### ISSUE TITLE
Error in rcategor and rcategor.int for large numbers of groups

### ISSUE THREAD

**Issue by bsaul** [osofr/simcausal#1] opened 2015-07-08 18:37 UTC
I'd like to use `rcategor` (or `rcategor.int`) to assign individuals to a large number of categories, but the following example illustrates an error:

```
D <- DAG.empty()
D1 <- D + node('group',
              distr = 'rcategor.int',
              probs = rep(1/50, 50)) 
D2 <- D + node('group',
               distr = 'rcategor.int',
               probs = rep(1/55, 55)) 
D1 <- set.DAG(D1)
D2 <- set.DAG(D2)
```

D1 is fine. D2, however, presents the following error:
![image](https://cloud.githubusercontent.com/assets/4882990/8578740/6e4857da-257e-11e5-8646-bb72b137a231.png)

I'm just starting to play with the package. It's great so far!

**Comment by osofr** [comment] 2015-07-08 19:13
Thanks for catching this. Before I get to the bottom of this,  as a quick fix, you can replace 
`probs = rep(1/55, 55))`
 with 
`probs = .(rep(1/55, 55)))`
This will force immediate evaluation of the expression inside .() and seems to work. It won't work though if the expression in probs includes other node names.

**Comment by bsaul** [comment] 2015-07-08 19:14
Great. Thanks!

**Comment by osofr** [comment] 2015-07-10 00:29
Fixed now, should work as intended. Thanks for reporting.

**Closed as completed by osofr** 2015-07-10 00:29 UTC
